### ISSUE TITLE
AttributeError: 'list' object has no attribute 'keys' when attemping to run the sample with Python 3.7.0 and all dependencies listed in the readme with exact versions. 

### ISSUE THREAD

**Issue by Chris-Hamid** [PerfectoMobileSA/Robotframework_Perfecto_demo#3]
C:\Users\CHamid\Downloads\Robotframework_Perfecto_demo>python -m robot testPerfectoDevices-Demo.robot
==============================================================================
testPerfectoDevices-Demo
==============================================================================
[ WARN ] Keyword 'Capture Page Screenshot' could not be run on failure: No application is open
Demo test on iphone                                                   | FAIL |
AttributeError: 'list' object has no attribute 'keys'
------------------------------------------------------------------------------
testPerfectoDevices-Demo                                              | FAIL |
1 test, 0 passed, 1 failed
==============================================================================
Output:  C:\Users\CHamid\Downloads\Robotframework_Perfecto_demo\output.xml
Log:     C:\Users\CHamid\Downloads\Robotframework_Perfecto_demo\log.html
Report:  C:\Users\CHamid\Downloads\Robotframework_Perfecto_demo\report.html

**Comment by denghj** [comment]
Hi Chris,

Can you please send me the following three log files of your failed TC so I
can investigate?

Output: C:\Users\CHamid\Downloads\Robotframework_Perfecto_demo\*output.xml*
Log: C:\Users\CHamid\Downloads\Robotframework_Perfecto_demo*\**log.html*
Report: C:\Users\CHamid\Downloads\Robotframework_Perfecto_demo\*report.html*

*Thanks.*
*Jack*
